import { chromium } from 'playwright-core';
const executablePath = process.env.CHROME_BIN;
if (!executablePath) throw new Error('Set CHROME_BIN to a Chromium/Chrome executable before running test:e2e.');
const browser = await chromium.launch({ headless: true, executablePath });
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
await page.goto(process.env.APP_URL || 'http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
await page.getByRole('heading', { name: '財務總覽' }).waitFor();
await page.screenshot({ path: process.env.DESKTOP_SHOT || 'desktop.png', fullPage: true });
await page.locator('input[name="expense"]').fill('240');
await page.getByRole('button', { name: /確認送出/ }).click();
await page.getByText('已儲存到這台裝置。').waitFor();
await page.reload({ waitUntil: 'networkidle' });
await page.getByText('240', { exact: false }).first().waitFor();
await page.getByRole('button', { name: /總計餘額/ }).click();
await page.getByRole('heading', { name: '統計與流水' }).waitFor();
await page.getByRole('button', { name: '流水', exact: true }).click();
await page.getByRole('button', { name: /未註記/ }).first().click();
await page.getByRole('heading', { name: '修改流水' }).waitFor();
await page.getByRole('button', { name: '關閉' }).click();
await page.getByRole('button', { name: '資料與同步' }).first().click();
await page.getByRole('heading', { name: '資料與同步' }).waitFor();
await page.getByRole('button', { name: '關閉' }).click();
await page.setViewportSize({ width: 412, height: 915 });
await page.getByRole('button', { name: '新增' }).click();
await page.getByRole('heading', { name: '新增交易' }).waitFor();
await page.getByRole('button', { name: '交易' }).click();
await page.getByRole('heading', { name: '近期交易' }).waitFor();
await page.getByRole('button', { name: '新增' }).click();
await page.screenshot({ path: process.env.MOBILE_SHOT || 'mobile.png', fullPage: true });
await browser.close();
