import { useCallback, useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { all, put, settingsObject } from './lib/db.js';
import { calculate, categories, defaultAccounts, expenseCategories, num } from './lib/ledger.js';

const money = n => new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n);
const today = () => new Date().toLocaleDateString('sv-SE');
const localDate = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function App() {
  const [transactions,setTransactions]=useState([]), [settings,setSettings]=useState({}), [notice,setNotice]=useState(''), [syncOpen,setSyncOpen]=useState(false), [update,setUpdate]=useState(false);
  const accounts=settings.accounts || defaultAccounts;
  const ledger=useMemo(()=>calculate(transactions,accounts),[transactions,accounts]);
  const saveSetting=useCallback(async(key,value)=>{await put('settings',{key,value});setSettings(s=>({...s,[key]:value}));},[]);
  const saveTransaction=useCallback(async tx=>{await put('transactions',tx);setTransactions(t=>[...t.filter(x=>x.id!==tx.id),tx]);},[]);
  useEffect(()=>{Promise.all([all('transactions'),all('settings')]).then(([t,s])=>{setTransactions(t);setSettings(settingsObject(s));}); const f=()=>setUpdate(true);window.addEventListener('book-update-ready',f);return()=>window.removeEventListener('book-update-ready',f);},[]);
  const add=async event=>{event.preventDefault();const v=Object.fromEntries(new FormData(event.currentTarget));if(!num(v.expense)&&!num(v.income))return setNotice('請填入支出或收入。');const tx={id:crypto.randomUUID(),sequence:Math.max(0,...transactions.map(x=>x.sequence||0))+1,date:v.date,account:v.account,category:v.category,reason:v.reason,expense:num(v.expense),income:num(v.income),updatedAt:new Date().toISOString(),deleted:false};await saveTransaction(tx);event.currentTarget.reset();setNotice('交易已儲存於本機資料庫。');};
  const importBook=async file=>{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]],get=(r,c)=>ws[XLSX.utils.encode_cell({r,c})]?.v,text=x=>x==null?'':String(x);const h=Array.from({length:58},(_,c)=>text(get(0,c)));const nextAccounts=[...new Set([...accounts,...h.slice(9,17),h[53],h[54],h[55],h[57]].filter(Boolean))];const range=XLSX.utils.decode_range(ws['!ref']),items=[];for(let r=1;r<=range.e.r;r++){const raw=get(r,0);if(!raw)continue;const date=raw instanceof Date?localDate(raw):typeof raw==='number'?XLSX.SSF.format('yyyy-mm-dd',raw):text(raw).slice(0,10);const tx={id:`legacy-${r+1}-${date}`,sequence:r+1,date,account:text(get(r,1)),category:text(get(r,2)),reason:text(get(r,3)),expense:num(get(r,4)),income:num(get(r,5)),updatedAt:new Date().toISOString(),deleted:false};if(tx.account||tx.category||tx.expense||tx.income)items.push(tx);}for(const tx of items)await put('transactions',tx);await saveSetting('accounts',nextAccounts);setTransactions(t=>[...new Map([...t,...items].map(x=>[x.id,x])).values()]);setNotice(`已匯入 ${items.length} 筆舊帳本交易。`);};
  const backup=()=>{const blob=new Blob([JSON.stringify({schema:4,accounts,transactions,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:`daily-book-ver4-${today()}.json`});a.click();URL.revokeObjectURL(a.href);};
  return <><aside><b>日常記帳 Ver.4</b><button>總覽</button><button onClick={()=>document.querySelector('#transactions').scrollIntoView({behavior:'smooth'})}>交易明細</button><button onClick={()=>setSyncOpen(true)}>資料與同步</button><small>IndexedDB · {ledger.rows.length} 筆交易</small></aside><main><header><h1>總覽</h1><button onClick={()=>setSyncOpen(true)}>資料與同步</button></header>{update&&<div className="update">已有新版可用。重新整理後更新。<button onClick={()=>location.reload()}>更新</button></div>}<section className="summary"><article><span>總額</span><strong>{money(ledger.total)}</strong><small>沿用舊試算表的順序與轉帳計算規則</small></article><article className="accounts"><h2>帳戶餘額</h2><div>{accounts.map(a=><p key={a}><span>{a}</span><b className={ledger.balances[a]<0?'negative':''}>{money(ledger.balances[a])}</b></p>)}</div></article></section><section className="grid"><article><h2>本月支出分析</h2><strong className="spent">{money(Math.abs(ledger.month.total))}</strong><p>差額 {money(ledger.month.diff)} · 存 {money(ledger.month.save)}</p>{expenseCategories.map(c=><div className="category" key={c}><span>{c}</span><i style={{width:`${Math.min(100,Math.abs(ledger.month.values[c])/5000*100)}%`}}></i><b>{money(Math.abs(ledger.month.values[c]))}</b></div>)}</article><form onSubmit={add}><h2>快速新增交易</h2><label>日期<input name="date" type="date" defaultValue={today()} required/></label><label>帳戶<select name="account">{accounts.map(a=><option key={a}>{a}</option>)}</select></label><label>分類<select name="category">{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>原因備註<input name="reason"/></label><label>支出<input name="expense" type="number" min="0" step="any"/></label><label>收入<input name="income" type="number" min="0" step="any"/></label><button className="primary">新增交易</button></form></section><section id="transactions"><h2>近期交易</h2><table><thead><tr><th>日期</th><th>帳戶</th><th>分類</th><th>原因</th><th>支出</th><th>收入</th></tr></thead><tbody>{ledger.rows.slice(-30).reverse().map(t=><tr key={t.id}><td>{t.date}</td><td>{t.account}</td><td>{t.category}</td><td>{t.reason||'—'}</td><td>{t.expense?money(t.expense):'—'}</td><td>{t.income?money(t.income):'—'}</td></tr>)}</tbody></table></section>{syncOpen&&<dialog open><button className="close" onClick={()=>setSyncOpen(false)}>×</button><h2>資料與同步</h2><p>交易主資料保存在此裝置的 IndexedDB。Google Drive OAuth 與備份設定保存於 LocalStorage／設定資料庫。</p><input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files[0]&&importBook(e.target.files[0])}/><button onClick={backup}>下載 JSON 備份</button><label>Google OAuth Client ID<input defaultValue={settings.googleClientId||''} onBlur={e=>saveSetting('googleClientId',e.target.value.trim())}/></label><p className="muted">設定 Client ID 後即可使用 Google Identity Services 與 Drive API 同步；此公開版不會儲存任何 OAuth secret。</p></dialog>}{notice&&<div className="toast" onAnimationEnd={()=>setNotice('')}>{notice}</div>}</main></>;
}
